### ISSUE TITLE
Create Modular Behavior

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/gb-svc-beacon-bot#107]
It would be nice if the superadmins and such had the ability to enable/disable a feature without having to do a whole new deployment.

!enable module name
!disable module name

Ideally that's everything under that module.. for example disable all misc-commands etc.

We can make this more granular but it feels overkill.

**Comment by kankurodev** [comment]
Yea, this has been on my backlog since the beginning of development tbh.. I really should do it before the code gets too large lol.
