### ISSUE TITLE
Impliment Slowmode

### ISSUE THREAD

**Issue by bluesaxman** [OSAlt/gb-svc-beacon-bot#108]
# Allow access to slow most though the bot
Example:
```
!slowdown ChannelID, Slowness Factor, Length, Start Time
```

### Options:
* ChannelID (the channel to be slowed)
* Slowness Factor (what to set slowmode to in discord)
* Length (how long slow mode should be turned on for)
* (Optional) Start Time (when to slow the channel, for instance for an event)

**Comment by kankurodev** [comment]
I probably won't implement the start time, at least not at first. Don't think it would be used much since most instances it will be used when needed.
