### ISSUE TITLE
Temporary Voice Channels

### ISSUE THREAD

**Issue by FlunseyTheFox** [OSAlt/gb-svc-beacon-bot#116]
This command will create a private voice channel and use permissions to not allow anyone to join the channel except who sent the message. Then, the person who made the channel can use a command to whitelist people so they can have a private voice channel without having to worry about anyone they don't want entering the channel. Once everyone leaves voice, then the bot will auto delete the voice channel.

**Comment by kankurodev** [comment]
Done, but not exactly as you suggested.
